// Auto-generated by export_to_web.py — DO NOT EDIT BY HAND
// Generated at: 2026-04-29 11:05:58+0800
// Source base: PnRtbGmTpaVXwDsWBWPcPaEpnwh
// Groups: 1 · Messages (displayed): 5 · Members: 2

const __APP_DATA__ = {
  "TEAM": [
    {
      "id": "ou_2aa8165f80f27625251a6ad88f1da2e7",
      "name": "用户783094",
      "color": "oklch(0.68 0.13 73)",
      "msgs": 1
    }
  ],
  "GROUPS": [
    {
      "id": "g1",
      "chat_id": "oc_d7be794f121f63fdf5b1b4038cb651ea",
      "name": "自用的飞书购买咨询群",
      "company": "自用的飞书购买咨询群",
      "avatar": {
        "initial": "自",
        "bg": "oklch(0.82 0.09 81)",
        "ring": "oklch(0.68 0.13 81)",
        "fg": "oklch(0.30 0.08 81)"
      },
      "owner": {
        "id": "owner-0",
        "name": "用户783094",
        "role": "群主",
        "color": "oklch(0.68 0.13 336)"
      },
      "memberCount": 2,
      "clientCount": 1,
      "teammateCount": 1,
      "todayMsgs": 5,
      "weekMsgs": 5,
      "unread": 5,
      "lastMinutesAgo": 6,
      "unreplyMinutes": 0,
      "pinned": true,
      "sentiment": {
        "key": "concern",
        "label": "顾虑",
        "color": "oklch(0.78 0.14 75)",
        "soft": "oklch(0.96 0.05 75)"
      },
      "tags": [
        "咨询",
        "购买"
      ],
      "members": [
        {
          "id": "ou_2aa8165f80f27625251a6ad88f1da2e7",
          "name": "用户783094",
          "company": "Chorus 团队",
          "role": "客服",
          "side": "team",
          "avatar": {
            "initial": "用",
            "bg": "oklch(0.82 0.09 336)",
            "ring": "oklch(0.68 0.13 336)",
            "fg": "oklch(0.30 0.08 336)"
          }
        },
        {
          "id": "ou_6db3209e799b66dd96ba39b3837d025a",
          "name": "杜小龙",
          "company": "自用的飞书购买咨询群",
          "role": "客户",
          "side": "client",
          "avatar": {
            "initial": "杜",
            "bg": "oklch(0.82 0.09 134)",
            "ring": "oklch(0.68 0.13 134)",
            "fg": "oklch(0.30 0.08 134)"
          }
        }
      ],
      "messages": [
        {
          "id": "om_x100b50237319d480b363b07db5e1cc5",
          "from": {
            "id": "unknown-0-0",
            "name": "未知成员",
            "company": "—",
            "role": "—",
            "side": "client",
            "avatar": {
              "initial": "?",
              "bg": "oklch(0.82 0.09 63)",
              "ring": "oklch(0.68 0.13 63)",
              "fg": "oklch(0.30 0.08 63)"
            }
          },
          "text": "飞书智能助手 invited 用户783094 to the chat.",
          "time": 1777431517000
        },
        {
          "id": "om_x100b5023732e20acb3d689d49768c18",
          "from": {
            "id": "unknown-0-1",
            "name": "未知成员",
            "company": "—",
            "role": "—",
            "side": "client",
            "avatar": {
              "initial": "?",
              "bg": "oklch(0.82 0.09 63)",
              "ring": "oklch(0.68 0.13 63)",
              "fg": "oklch(0.30 0.08 63)"
            }
          },
          "text": "飞书智能助手 invited 杜小龙 to the group. New members can view all chat history.",
          "time": 1777431518000
        },
        {
          "id": "om_x100b50237323e508b4c7bf7d2910f03",
          "from": {
            "id": "unknown-0-2",
            "name": "未知成员",
            "company": "—",
            "role": "—",
            "side": "client",
            "avatar": {
              "initial": "?",
              "bg": "oklch(0.82 0.09 63)",
              "ring": "oklch(0.68 0.13 63)",
              "fg": "oklch(0.30 0.08 63)"
            }
          },
          "text": "飞书智能助手 invited 飞书多维表格智能助理 to the group. New members can view all chat history.",
          "time": 1777431518000
        },
        {
          "id": "om_x100b50237339a508b103b187be557cf",
          "from": {
            "id": "cli_a8dd4783023a900d",
            "name": "未知成员",
            "company": "—",
            "role": "—",
            "side": "client",
            "avatar": {
              "initial": "c",
              "bg": "oklch(0.82 0.09 119)",
              "ring": "oklch(0.68 0.13 119)",
              "fg": "oklch(0.30 0.08 119)"
            }
          },
          "text": "@_user_1您好，为了让您进一步了解飞书，飞书官方销售经理@_user_2已加入群中，将为您提供一对一的功能方案介绍 💪\n如果您是为企业考察/购买飞书可以发送数字【1】，我们会为您提供企业专属咨询服务",
          "time": 1777431519000
        },
        {
          "id": "om_x100b5023714388a4c3906500204298a",
          "from": {
            "id": "ou_2aa8165f80f27625251a6ad88f1da2e7",
            "name": "用户783094",
            "company": "Chorus 团队",
            "role": "客服",
            "side": "team",
            "avatar": {
              "initial": "用",
              "bg": "oklch(0.82 0.09 336)",
              "ring": "oklch(0.68 0.13 336)",
              "fg": "oklch(0.30 0.08 336)"
            }
          },
          "text": "1",
          "time": 1777431545000
        }
      ],
      "topSpeakers": [
        {
          "name": "用户783094",
          "n": 1
        }
      ],
      "readStatus": {
        "read": 1,
        "total": 1
      }
    }
  ],
  "SENTIMENTS": [
    {
      "key": "happy",
      "label": "满意",
      "color": "oklch(0.74 0.11 155)",
      "soft": "oklch(0.95 0.03 155)"
    },
    {
      "key": "neutral",
      "label": "平稳",
      "color": "oklch(0.72 0.04 240)",
      "soft": "oklch(0.95 0.015 240)"
    },
    {
      "key": "concern",
      "label": "顾虑",
      "color": "oklch(0.78 0.14 75)",
      "soft": "oklch(0.96 0.05 75)"
    },
    {
      "key": "angry",
      "label": "不满",
      "color": "oklch(0.72 0.13 20)",
      "soft": "oklch(0.96 0.035 20)"
    }
  ],
  "TAGS": [
    "咨询",
    "购买",
    "售后",
    "实施中",
    "KA客户",
    "多人群",
    "活跃"
  ],
  "DASHBOARD": {
    "totalGroups": 1,
    "activeGroups": 1,
    "todayMsgs": 5,
    "avgResponseMin": 4.2,
    "pendingClient": 0,
    "stalled": [],
    "sentimentBreakdown": [
      {
        "key": "happy",
        "label": "满意",
        "color": "oklch(0.74 0.11 155)",
        "soft": "oklch(0.95 0.03 155)",
        "count": 0
      },
      {
        "key": "neutral",
        "label": "平稳",
        "color": "oklch(0.72 0.04 240)",
        "soft": "oklch(0.95 0.015 240)",
        "count": 0
      },
      {
        "key": "concern",
        "label": "顾虑",
        "color": "oklch(0.78 0.14 75)",
        "soft": "oklch(0.96 0.05 75)",
        "count": 1
      },
      {
        "key": "angry",
        "label": "不满",
        "color": "oklch(0.72 0.13 20)",
        "soft": "oklch(0.96 0.035 20)",
        "count": 0
      }
    ],
    "speakerDist": [
      {
        "id": "ou_2aa8165f80f27625251a6ad88f1da2e7",
        "name": "用户783094",
        "color": "oklch(0.68 0.13 73)",
        "msgs": 1
      }
    ],
    "hourlyMsgs": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      5,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  }
};

function hashHue(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) | 0;
  return ((h % 360) + 360) % 360;
}

function avatarFor(name, tone = 60) {
  const h = hashHue(name || "?");
  return {
    initial: (name || "?").slice(0, 1),
    bg: `oklch(0.82 0.09 ${h})`,
    ring: `oklch(0.68 0.13 ${h})`,
    fg: `oklch(0.30 0.08 ${h})`,
  };
}

function formatRelative(ms) {
  const diff = (Date.now() - ms) / 1000;
  if (diff < 60) return "刚刚";
  if (diff < 3600) return `${Math.floor(diff / 60)} 分钟前`;
  if (diff < 86400) return `${Math.floor(diff / 3600)} 小时前`;
  return `${Math.floor(diff / 86400)} 天前`;
}

function formatTime(ms) {
  const d = new Date(ms);
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}

function buildSummary(group) {
  const pct = Math.min(100, Math.round((group.todayMsgs / Math.max(1, group.weekMsgs || 1)) * 100));
  const mood = group.sentiment.label;
  const hasMessages = group.messages && group.messages.length > 0;
  const topics = hasMessages
    ? Array.from(new Set(
        group.messages.flatMap(m =>
          (m.text || "").replace(/[\s\n\r]+/g, "").match(/[\u4e00-\u9fa5]{2,4}/g) || []
        )
      )).slice(0, 5)
    : ["暂无话题"];

  const actions = [];
  if (group.unreplyMinutes > 60) {
    actions.push({ who: group.owner.name, todo: `尽快回复客户最新消息（已 ${Math.floor(group.unreplyMinutes / 60)}h${group.unreplyMinutes % 60}m 未回）`, due: "今日" });
  }
  if (group.todayMsgs === 0) {
    actions.push({ who: group.owner.name, todo: "今日群内无消息，主动关怀客户一次", due: "本周" });
  }
  if (actions.length === 0) {
    actions.push({ who: group.owner.name, todo: `跟进${topics[0] || "客户需求"}`, due: "今日 18:00" });
  }

  const hl = [
    `客户整体情绪：${mood}${topics.length ? `（关键词：${topics.slice(0, 2).join("、")}）` : ""}`,
    `今日消息 ${group.todayMsgs} 条 · 本周 ${group.weekMsgs} 条`,
    group.unreplyMinutes > 60
      ? `⚠️ 有一条客户消息已超过 ${group.unreplyMinutes} 分钟未回复`
      : (hasMessages ? `最近一次互动：${formatRelative(Date.now() - group.lastMinutesAgo * 60 * 1000)}` : "今日暂无消息，建议主动跟进"),
  ];

  return { topics, actions, highlights: hl, activityPct: pct };
}

window.AppData = {
  ...__APP_DATA__,
  formatRelative,
  formatTime,
  buildSummary,
  avatarFor,
};
